server.port=8081
spring.r2dbc.url=r2dbc:postgresql://localhost:5432/ride_prices
spring.r2dbc.username=postgres
spring.r2dbc.password=postgres

spring.sql.init.mode=always
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://localhost:8080/realms/weeky-realm/protocol/openid-connect/certs
logging.level.org.springframework.security=DEBUG